application:
  id: bk-spring-batch-tasklet
  version: 1.0

spring:
  application:
    name: bk-spring-batch-tasklet
  profiles:
    active: local
  jpa:
    open-in-view: false # Open Session in View
  batch:
    jdbc:
      initialize-schema: always
    job:
      name: ${job.name:NONE}
      enabled: true

  datasource:
    batch:
      url: jdbc:mysql://localhost:33061/batch?autoReconnect=true&serverTimezone=UTC
      username: root
      password: 'P@ssw0rd'
      driver-class-name: com.mysql.cj.jdbc.Driver
    business:
      url: jdbc:mysql://localhost:33061/report?autoReconnect=true&serverTimezone=UTC
      username: root
      password: 'P@ssw0rd'
      driver-class-name: com.mysql.cj.jdbc.Driver
